---
title: "TrajectoryAnalysis_CD4_Tcells"
author: "astridhofman7"
date: "2025-01-23"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## Introduction

```{r error=TRUE}

library(monocle3)

set.seed(42)
seu <- readRDS("/data/ashofm/PRECISE/cd4_tcells/cd4_tcell_reclustered.RDS")
DefaultAssay(seu) <- "SCT"
```



```{r error=TRUE}
# create gene metadata data.frame

feature_names <- as.data.frame(rownames(seu))
rownames(feature_names) <- rownames(seu)
colnames(feature_names) <- "gene_short_name"

# initiate monocle object from seurat count table 
seu_monocl <- monocle3::new_cell_data_set(Seurat::GetAssayData(seu,
                                                               layer = "counts"),
                                          cell_metadata = seu@meta.data,
                                          gene_metadata = feature_names)

```


```{r error=TRUE}
seu_monocl <- monocle3::preprocess_cds(seu_monocl, num_dim = 30)
#seu_monocl <- align_cds(seu_monocl, alignment_group = "batch")
monocle3::plot_pc_variance_explained(seu_monocl)


```

```{r error=TRUE}

seu_monocl <- monocle3::reduce_dimension(seu_monocl, umap.n_neighbors = 20, umap.min_dist = 0.7)

```

```{r error=TRUE}
monocle3::plot_cells(seu_monocl, 
                     color_cells_by = "orig.ident", 
                     cell_size = 1, 
                     show_trajectory_graph = FALSE)

```



```{r error=TRUE}

seu_monocl <- monocle3::cluster_cells(seu_monocl, , resolution=0.0009)
monocle3::plot_cells(seu_monocl, label_cell_groups = T)

```

```{r error=TRUE}
monocle3::plot_cells(seu_monocl, genes = c("CCR7", "SELL"), 
                     cell_size = 1,
                     show_trajectory_graph = FALSE,
                     scale_to_range = FALSE)

monocle3::plot_cells(seu_monocl, genes = c("FOXP3"), 
                     cell_size = 1,
                     show_trajectory_graph = FALSE,
                     scale_to_range = FALSE)

```

```{r error=TRUE}

seu_monocl <- monocle3::learn_graph(seu_monocl)
```


```{r error=TRUE}
seu_monocl <- monocle3::order_cells(seu_monocl)
trajectory <- monocle3::plot_cells(seu_monocl,
                     color_cells_by = "pseudotime", cell_size = 1, show_trajectory_graph = F)
ggsave("/data/ashofm/PRECISE/cd4_tcells/TrajectoryAnalysis/trajectory.png", trajectory, dpi = 600)
trajectory
```

```{r error=TRUE}
pr_test <- graph_test(seu_monocl, 
                      neighbor_graph = "principal_graph")

# order by test statistic
pr_test <- pr_test[order(pr_test$morans_test_statistic, 
                         decreasing = TRUE),]

View(pr_test)
```

